language: python

matrix:
  include:
    - name: Python 2.7
      python: "2.7"
      before_install:
        - pip install coveralls pylint
      env: COVERAGE="--with-coverage --cover-package=rebench"
      after_success:
        coveralls
    - name: Python 3.7
      dist: bionic
      python: "3.7"
      before_install:
        - pip install coveralls pylint
    - name: Python 3.8-dev (normal)
      python: "3.8-dev"
      dist: xenial
      before_install:
        - pip install pylint
    - name: Python 3.8-dev (ruamel.yaml)
      python: "3.8-dev"
      dist: xenial
      before_install:
        - pip install pylint
        - pip install ruamel.yaml
    # PyPy versions
    - name: PyPy 2.7
      python: pypy
      env: DO_LINT="echo On PyPy, we won't "
    - name: PyPy 3.x
      python: pypy3
      env: DO_LINT="echo On PyPy, we won't "

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - time

install:
  - pip install .

# command to run tests
script:
 - nosetests ${COVERAGE}
 - (cd rebench && rebench -N ../rebench.conf e:TestRunner2)
 - ${DO_LINT} pylint rebench
