language: python

python:
  - "2.7"

# install dependencies
before_install:
  - sudo apt-get install -qq python-scipy

install:
  - pip -q install PyYAML
  #- pip install numpy
  #- pip install scipy
# TODO: check whether we can do something like the proposed:
#   "pip install -r requirements.txt --use-mirrors"

# command to run tests
script: nosetests
