site_name: 'ReBench: Execute and Document Benchmarks Reproducibly'
site_description: ReBench Project documentation
site_author: ReBench contributors

pages:
  - 'ReBench: Execute and Document Benchmarks Reproducibly': index.md
  - Usage:         usage.md
  - Configuration: configuration.md
  - Development:
     - Release Steps: release.md
  - License:    LICENSE.md
  - Change Log: CHANGELOG.md

markdown_extensions:
  - toc:
      permalink: True
