name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '2.7', '3.7', '3.9', 'pypy3' ]
        yaml-parser: ['', 'ruamel']
        include:
          - python-version: 2.7
            coverage: "--cov=rebench"
        exclude:
          - python-version: 2.7
            yaml-parser: ruamel
          - python-version: 3.9
            yaml-parser: ruamel
          - python-version: pypy3
            yaml-parser: ruamel
    name: Python ${{ matrix.python-version }} ${{ matrix.yaml-parser }}
    steps:
      - name: Checkout ReBench
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install PyTest
        run: pip install pytest

      - name: Install ruamel.yaml
        run: pip install ruamel.yaml
        if: matrix.yaml-parser == 'ruamel'

      - name: Install coverage and coveralls
        run: pip install pytest-cov coveralls
        if: matrix.coverage

      - name: Install ReBench dependencies
        run: pip install .

      - name: Run tests
        run: |
          pytest ${{ matrix.coverage }}
          (cd rebench && rebench ../rebench.conf e:TestRunner2)

      - name: Install and run pylint
        run: |
          pip install pylint
          pylint rebench
        if: matrix.python-version == '3.9'

      - name: Upload coverage results to Coveralls
        run: coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        if: ${{ matrix.coverage && env.COVERALLS_REPO_TOKEN != '' }}
