name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '2.7', '3.7', '3.11', 'pypy3.9' ]
        yaml-parser: ['', 'ruamel']
        include:
          - python-version: 2.7
            coverage: "--cov=rebench"
        exclude:
          - python-version: 2.7
            yaml-parser: ruamel
          - python-version: 3.11
            yaml-parser: ruamel
          - python-version: pypy3
            yaml-parser: ruamel
    name: Python ${{ matrix.python-version }} ${{ matrix.yaml-parser }}
    steps:
      - name: Checkout ReBench
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install PyTest
        run: pip install pytest

      - name: Install ruamel.yaml
        run: pip install ruamel.yaml
        if: matrix.yaml-parser == 'ruamel'

      - name: Install coverage and coveralls
        run: pip install pytest-cov coveralls
        if: matrix.coverage

      - name: Install ReBench dependencies
        run: pip install .

      - name: Run tests
        run: |
          pytest ${{ matrix.coverage }}
          (cd rebench && rebench ../rebench.conf e:TestRunner2)

      - name: Install and run pylint
        run: |
          pip install pylint
          pylint rebench
        if: matrix.python-version == '3.11'

      - name: Upload coverage results to Coveralls
        run: coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        if: ${{ matrix.coverage && env.COVERALLS_REPO_TOKEN != '' }}

  test-docker:
    name: Test ReBench in Docker
    runs-on: ubuntu-latest
    container:
      image: python:3

    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Make Python to be Python3
        run: ln -s /usr/bin/python3 /usr/bin/python && ln -s /usr/bin/pip3 /usr/bin/pip

      - name: Install Time Command
        run: |
          apt-get update
          apt-get install -y --no-install-recommends time

      - name: Checkout ReBench
        uses: actions/checkout@v3

      - name: Install PyTest
        run: pip install pytest

      - name: Install ReBench dependencies
        run: pip install .

      - name: Run Test Run
        run: (cd rebench && rebench ../rebench.conf e:TestRunner2)

      - name: Run Unit Tests
        run: python -m pytest
